language: scala

scala:
  - 2.12.3
  - 2.11.11

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: S3H0kMZ4rAqVe8KxKzVoC7G59CDRS3bRuTTOgKbSc3SnzoM+WiLEL6kfPKJRjfbIiw6nGQNFj3sQlfHbpTAbEr1ZO3o05IyUGMkGZx7fC4bGuGvifsrLbR5sX3MNrQoAjJMF50PQMJdBNn4Cu5Ka+BmXmCfnUC6lxqkWpVdOCSNtUuKp9mL3R1CTZT0jUyh2F9SVmZTFQx/xebf0WmnFVSTo8l0uRJXHa4tzNi439fXysc9c5TJpSses9BRbxxFDG2Wkyxr3d5vmjZ7RnfMFu/NZWW/89kfok5KPh61UOPDfAijbsigNd2Fpy7Gkk6g0PCGhZbDJ19y7HEIszvKAbrby62bZZHog+UK2e1nA16TLygovOWezFILdta4l1r+03n/j4eV8oQe63ak+/fZOmCk/Ka9YfYd7xfY8O2gEdmReaLx73zKzuIspeZlNCm25yxx3aAAvejHDQqcBGLLmlc0XUw/tdcm3yC/XW1FtMh/8UiHb0nVv+1R9Y4w7HRIkgAd1NXIQ+addnSOJRvoapCI/6XAHPKCBduXC/yUKieyguzrWT971ckGMP1LTVrLyZ1XjRnlswCqXhROd5RxJMmcCoTHWY3LalodR7tceBGpdTGN2lTVlVKE+2dIIkdAwvH32rSMKNmeSOuIMNA4kCFx0smCYoL3Q0vsNBPCdvlo=
  - secure: WtrvTHVttPP4YJD+sqWnrGc2Lxmr+tCXTTWr/F8OU91JQpJd7OG7sWsxpI8/DIheLz3OwExzMNKsJActD9p0u/Wz41Gc26bimadhqY5g596bQD7ogGGDp1PpFSJRIgJU1ps12uFcnRzxeJbJ3tv+0e85WELLJDVQGAiMv8yQtwdiSnAYbWRNZa4IuJbZ1DO+uGLzrHseH97sxAK4DwcrQXXVKNB91B+Q+cCpVSxhX6JAA3j30isFQ6DyN8SgA1ywwLsj1IkRP4iw4EPa+Dk8jOtj9qisbfmAufncoiY+JZ8MRdjExMIBHf+Z5AzTw9KVkt98XDO0gf6cKfHYHZ0RxXelU1hRBBwAuN56aK2DPcuG/MYFQglTU9dnya4wP48+gDJKEvS7slovyrYrpDo5NtzkCwV3mdGiRL2c1AQiKA/xBd8KYN/7KNaN1oPiMhaScOof8iZxnQykZgj6mFdC+kXklC3xApSRZ7fnN33U37oL/kHllHAYF60bxH0Z3XTOOsl4vXqf09QRFq0fokK5qnI0gGHG/xX/oJfeQrK60ABnO8Rz0Z3j6FI579RBB9mOzQt9E8Czfc5FBiGH+fQ2siEHKVxgJWvzMhLGGMpg3u3PIT1YPkwV3eX+Er4DEC1GrMgxokzyt+au62aXPaw5lvgAiEOqZDd7W4sa8JmuxhI=
  - secure: Ee99sJGRatGFDrjYjSgxNINx6BKTENyEtErVNqouqwqmvy8I7IIaFRPmOFzDoGD2M3VAITY+jhZ0rY3wEkRitzPO7F41yVLslyQPJYmYJw3jx05GYQSNM83Hy1dZYIUPFDdzDi+yn4WtyhR/dPP8RtiWRYebvvXhZTq31FGem1bn7TLh2qTTG5J7/d3mgjEinzEoyomyiM04p+90PNaimKPVSaOIZz8n8E88gZ+NJqmCQK+j1m7hB9ttPFycWYBCpQKGU+ZtQKEMTjpI9Es4P3Uhh7Z2uqUZJcGmwIWR3byInAKxBh57xczEjXbjugVGT86+QX5UvGjtp2kg6xfwy1z24HUDWxVrBJkkO7jB6UaQFfGzOmhWyFtd/2RzWIcIfVgZ0bfvZnRjU7QtVG7vFwPxwMZjFZ45uJSnL/WyITA9xKP7Yq83axNQzVCYhFc6BxetWnpjlc4PBk6QI4vRJc34+bB+kKCrsCc7mKoZI1mkc0Eg+1D73FG+S6nZupp8InL5UqNVafVDNF3WYXnma0gKtAkJ/uoHusBc4GFsfi25CqRz+OsesIJ3ICAw/D2e+2dy9NYDCW0iZsuJcV+gHSOHF2dWy5Olxlhyw2841MeAbVa50uLB638XiV/7Cg8SAe3i6C5rkiwPuGWfuadTUvVdPJEpYaT4lGq2UHWPRe4=
  - secure: BCArYQqSKWdJoD04KmqCEEp8udkqrWWA8O9IRxRYnghnu84yFYsuRXFLC3z44luyfPJEXRRxSsTDqrp5lSXA9AdGMBtj0i7uXNpSQTGXJctktpDMIGeoTUpsWtHrg1NtcJkCXet3+MXPu7CMPVSwkqQPm71VPTRX5Fnn6CbXogwf1so4SG9d7ll18Q70KWb9x61IxRvn/XZftWHN7JLUtQkLfIY/ziRf3rVxAsH3JCCfw1TWWQSZ3V9glP/1XdbO8kvFZQ6YU7ZOq+u4LfGm4w0rRuUU8xLV2ATmFYQu7GeZLWNsdmRdV+lfPnrBVAQoS9lkEqbInhkSGD4AvXYdNFNpCfD6wwBJLhTmJm9g07TfebMrKg2eH8Wwg466tOKMPTitBh9me9SI9SXLH3JTJLRR7VuPYCoDpPPLJRGP2qYrvAV5Pjcr7LQnu4PX8Z4kM9IqFLIppEJghXeBqsHxtnk8Q2QXRhHobkkP7ClIhDgvvv7zCdrRqKSc8sHeSYhE59vlChDDCdWjrlrPIePVVJir9BGIJ62MBXsQzDtDriWQx762lFP0VvncOTDEX3Xq2Tvxq+xv45X5CH/yHqUV+8Bf5xsTWPiFqFyq45k9cHMPtgQHU8nF5GiEGxfMt0VnpkKlWKsur9XcbeWanLmr9TDqEpPi3fh1IPdWdJJzajA=
